# Generated by Django 3.1.5 on 2021-01-18 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webui', '0002_delete_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=100)),
                ('park_type', models.CharField(max_length=100)),
                ('park_status', models.CharField(max_length=100)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
